export const curriculum = [
  [
    "TRN-01",
    "Welcome to the Organisation",
    "Purpose, history and how the organisation creates value",
    "8 min",
  ],
  [
    "TRN-02",
    "Vision, Mission & Core Values",
    "Connect daily decisions to the organisation's direction",
    "10 min",
  ],
  [
    "TRN-03",
    "Leadership & Organisation Structure",
    "Know the leadership team, departments and reporting routes",
    "9 min",
  ],
  [
    "TRN-04",
    "Culture, Conduct & Expected Behaviour",
    "Apply workplace standards in realistic situations",
    "12 min",
  ],
  [
    "TRN-05",
    "Code of Ethics",
    "Recognise conflicts, gifts, misconduct and speak-up routes",
    "12 min",
  ],
  [
    "TRN-06",
    "Information Security & Confidentiality",
    "Protect accounts, devices, data and confidential information",
    "18 min",
  ],
  [
    "TRN-07",
    "Data Privacy & Compliance",
    "Handle personal and regulated data lawfully",
    "15 min",
  ],
  [
    "TRN-08",
    "Communication Etiquette",
    "Use email, WhatsApp, phone and meetings professionally",
    "16 min",
  ],
  [
    "TRN-09",
    "HR & Office Policies",
    "Find, understand and acknowledge current policies",
    "12 min",
  ],
  [
    "TRN-10",
    "Leave & Attendance",
    "Submit leave and regularisation through the approved route",
    "11 min",
  ],
  [
    "TRN-11",
    "Expenses & Reimbursement",
    "Prepare complete, accurate and timely claims",
    "10 min",
  ],
  [
    "TRN-12",
    "Asset Allocation, Use & Return",
    "Request, protect, transfer and return company assets",
    "14 min",
  ],
  [
    "TRN-13",
    "IT Support & Access",
    "Use tickets, priority rules and access approval correctly",
    "12 min",
  ],
  [
    "TRN-14",
    "Procurement & Vendor Onboarding",
    "Follow purchasing, due-diligence and approval controls",
    "15 min",
  ],
  [
    "TRN-15",
    "Escalation Matrix",
    "Escalate with evidence through the defined hierarchy",
    "10 min",
  ],
  [
    "TRN-16",
    "Performance Reviews",
    "Prepare goals, evidence, feedback and development actions",
    "12 min",
  ],
  [
    "TRN-17",
    "Learning & Development",
    "Use role pathways, mentoring and learning opportunities",
    "8 min",
  ],
  [
    "TRN-18",
    "Employee Benefits",
    "Understand eligibility, enrolment and support contacts",
    "9 min",
  ],
  [
    "TRN-19",
    "Ownership, Task Closure & Handover",
    "Close work with evidence, documentation and clear accountability",
    "14 min",
  ],
  [
    "TRN-20",
    "Document & Records Discipline",
    "Name, approve, store and retain documents correctly",
    "13 min",
  ],
  [
    "TRN-21",
    "Meetings & Collaboration",
    "Run purposeful meetings with decisions, owners and due dates",
    "10 min",
  ],
  [
    "TRN-22",
    "Frequently Asked Questions",
    "Resolve common operational questions independently",
    "8 min",
  ],
] as const;

export const responsibilityRows = [
  [
    "Applying for Leave",
    "Human Resources",
    "HR Executive",
    "Role holder",
    "HR backup",
    "hr-helpdesk@company.com",
    "2 business days",
    "HR Manager",
    "Head of HR",
    "SOP-01",
    "TRN-10",
  ],
  [
    "Attendance Regularisation",
    "Human Resources",
    "HR Executive",
    "Role holder",
    "HR backup",
    "hr-helpdesk@company.com",
    "2 business days",
    "HR Manager",
    "Head of HR",
    "SOP-01",
    "TRN-10",
  ],
  [
    "Payroll Query",
    "Human Resources",
    "Payroll Specialist",
    "Role holder",
    "Payroll backup",
    "payroll@company.com",
    "3 business days",
    "HR Manager",
    "Head of HR",
    "SOP-06",
    "TRN-09",
  ],
  [
    "Employee Referral",
    "Human Resources",
    "Talent Acquisition Lead",
    "Role holder",
    "TA backup",
    "careers@company.com",
    "5 business days",
    "HR Manager",
    "Head of HR",
    "SOP-09",
    "TRN-03",
  ],
  [
    "Exit Process & Asset Return",
    "Human Resources",
    "HR Operations Lead",
    "Role holder",
    "HR backup",
    "hr-helpdesk@company.com",
    "As per notice",
    "HR Manager",
    "Head of HR",
    "SOP-05",
    "TRN-12",
  ],
  [
    "Laptop / Asset Request",
    "Information Technology",
    "IT Asset Coordinator",
    "Role holder",
    "IT backup",
    "it-support@company.com",
    "3 business days",
    "IT Manager",
    "Head of IT",
    "SOP-02",
    "TRN-12",
  ],
  [
    "Damaged Equipment",
    "Information Technology",
    "IT Service Desk",
    "Role holder",
    "IT backup",
    "it-support@company.com",
    "4 business hours",
    "IT Manager",
    "Head of IT",
    "SOP-03",
    "TRN-13",
  ],
  [
    "IT Support Ticket",
    "Information Technology",
    "IT Support Engineer",
    "Role holder",
    "IT backup",
    "it-support@company.com",
    "1 business day",
    "IT Manager",
    "Head of IT",
    "SOP-03",
    "TRN-13",
  ],
  [
    "New Software Access",
    "Information Technology",
    "IT Administrator",
    "Role holder",
    "IT backup",
    "it-support@company.com",
    "2 business days",
    "IT Manager",
    "Head of IT",
    "SOP-04",
    "TRN-13",
  ],
  [
    "Password / Email Issue",
    "Information Technology",
    "IT Service Desk",
    "Role holder",
    "IT backup",
    "it-support@company.com",
    "4 business hours",
    "IT Manager",
    "Head of IT",
    "SOP-03",
    "TRN-06",
  ],
  [
    "Expense Reimbursement",
    "Finance",
    "Accounts Payable Specialist",
    "Role holder",
    "Finance backup",
    "expenses@company.com",
    "Next pay cycle",
    "Finance Manager",
    "CFO",
    "SOP-10",
    "TRN-11",
  ],
  [
    "Finance Approval",
    "Finance",
    "Finance Business Partner",
    "Role holder",
    "Finance backup",
    "finance@company.com",
    "3 business days",
    "Finance Manager",
    "CFO",
    "SOP-07",
    "TRN-11",
  ],
  [
    "Purchase Request",
    "Procurement",
    "Procurement Executive",
    "Role holder",
    "Procurement backup",
    "procurement@company.com",
    "5 business days",
    "Procurement Manager",
    "COO",
    "SOP-07",
    "TRN-14",
  ],
  [
    "Vendor Onboarding",
    "Procurement",
    "Vendor Management Lead",
    "Role holder",
    "Procurement backup",
    "vendors@company.com",
    "10 business days",
    "Procurement Manager",
    "COO",
    "SOP-08",
    "TRN-14",
  ],
  [
    "Travel Approval",
    "Administration",
    "Travel Coordinator",
    "Role holder",
    "Admin backup",
    "travel@company.com",
    "3 business days",
    "Admin Manager",
    "COO",
    "SOP-11",
    "TRN-09",
  ],
  [
    "Meeting Room Booking",
    "Administration",
    "Facilities Coordinator",
    "Role holder",
    "Admin backup",
    "facilities@company.com",
    "Same day",
    "Admin Manager",
    "COO",
    "SOP-12",
    "TRN-21",
  ],
  [
    "Visitor Management",
    "Administration",
    "Front Office Executive",
    "Role holder",
    "Admin backup",
    "reception@company.com",
    "1 business day",
    "Admin Manager",
    "COO",
    "SOP-13",
    "TRN-09",
  ],
  [
    "ID / Visiting Card Request",
    "Administration",
    "Admin Executive",
    "Role holder",
    "Admin backup",
    "admin@company.com",
    "5 business days",
    "Admin Manager",
    "COO",
    "SOP-14",
    "TRN-09",
  ],
  [
    "Contract / Legal Approval",
    "Legal & Compliance",
    "Legal Counsel",
    "Role holder",
    "Legal backup",
    "legal@company.com",
    "7 business days",
    "Legal Manager",
    "General Counsel",
    "SOP-15",
    "TRN-07",
  ],
  [
    "Recruitment Request",
    "Human Resources",
    "Talent Acquisition Lead",
    "Role holder",
    "TA backup",
    "careers@company.com",
    "5 business days",
    "HR Manager",
    "Head of HR",
    "SOP-09",
    "TRN-03",
  ],
  [
    "Marketing Support",
    "Marketing",
    "Marketing Operations Lead",
    "Role holder",
    "Marketing backup",
    "marketing@company.com",
    "5 business days",
    "Marketing Head",
    "COO",
    "SOP-16",
    "TRN-15",
  ],
  [
    "Sales Support",
    "Sales",
    "Sales Operations Lead",
    "Role holder",
    "Sales backup",
    "salesops@company.com",
    "3 business days",
    "Sales Head",
    "COO",
    "SOP-17",
    "TRN-15",
  ],
] as const;

export const mistakeCategories = [
  [
    "Communication",
    22,
    "Reply-all misuse, outdated signatures, unclear subjects, informal approvals, missing context",
  ],
  [
    "Security & privacy",
    24,
    "Personal email/devices, unlocked screens, weak MFA habits, oversharing, unsafe links",
  ],
  [
    "Assets & access",
    14,
    "Unapproved devices, bypassed allocation, shared credentials, late returns, shadow software",
  ],
  [
    "Documents & records",
    18,
    "Poor file names, local storage, wrong versions, missing approvals, weak retention",
  ],
  [
    "Process compliance",
    20,
    "Direct messaging instead of tickets, skipped approvals, incomplete forms, late claims",
  ],
  [
    "Ownership & closure",
    17,
    "Unclear owners, silent blockers, premature closure, weak handovers, no evidence",
  ],
  [
    "Meetings & collaboration",
    12,
    "No agenda, absent decisions, missing actions, late joining, poor follow-up",
  ],
] as const;

export const prioritySops = [
  ["SOP-01", "Leave & Attendance", "Human Resources", "Highest frequency"],
  [
    "SOP-02",
    "Asset Request, Allocation & Return",
    "Information Technology",
    "Lifecycle control",
  ],
  [
    "SOP-03",
    "IT Support & Incident Triage",
    "Information Technology",
    "Daily support",
  ],
  [
    "SOP-04",
    "Software Access & Permission",
    "Information Technology",
    "Security critical",
  ],
  ["SOP-05", "Employee Exit & Handover", "Human Resources", "Risk control"],
  ["SOP-06", "Payroll Query Resolution", "Human Resources", "Employee impact"],
  [
    "SOP-07",
    "Purchase & Finance Approval",
    "Finance / Procurement",
    "Spend control",
  ],
  ["SOP-08", "Vendor Onboarding & Changes", "Procurement", "Third-party risk"],
  ["SOP-09", "Recruitment & Referral", "Human Resources", "Growth process"],
  ["SOP-10", "Expense Reimbursement", "Finance", "High frequency"],
] as const;

export const blueprintItems = [
  [
    "01",
    "Detailed project plan",
    "Four phases from discovery to multi-organisation rollout",
    "Phase 0 → Phase 1 MVP → AI & analytics → 100+ organisations",
  ],
  [
    "02",
    "Complete training curriculum",
    "22 role-aware modules with objectives, duration and assessment format",
    "Core induction, security, conduct, processes, ownership and FAQs",
  ],
  [
    "03",
    "Common employee mistakes",
    "127 recurring mistakes grouped into seven operational categories",
    "Each mistake maps to training, SOP guidance and an accountable owner",
  ],
  [
    "04",
    "Responsibility matrix",
    "22 starter activities across HR, IT, Finance, Procurement, Admin, Legal, Marketing and Sales",
    "Owner, backup, contact, SLA, escalation, SOP and training links",
  ],
  [
    "05",
    "Initial SOP repository",
    "Governed taxonomy, standard template and first ten priority SOPs",
    "Owner, approver, version, controls, steps, evidence and review date",
  ],
  [
    "06",
    "SaaS architecture & workflow",
    "Next.js, FastAPI, LangGraph, PostgreSQL/pgvector, n8n and AWS",
    "Query → tenant scope → semantic retrieval → verified answer → escalation",
  ],
  [
    "07",
    "UI/UX prototype",
    "Employee, manager and administrator experiences in one responsive platform",
    "Search, learning, assessment, certificates, ownership, SOPs and analytics",
  ],
  [
    "08",
    "Training & assessment",
    "Learn → quiz → 80% pass → certificate → refresher → analytics",
    "Unlimited retakes with question-level insights and compliance evidence",
  ],
  [
    "09",
    "Implementation roadmap",
    "Task-level delivery plan with dependencies and acceptance gates",
    "Foundation, content, MVP, integrations, pilot, hardening and rollout",
  ],
  [
    "10",
    "Future scalability",
    "Tenant isolation and configurable organisation onboarding from day one",
    "org_id/RLS, tenant branding, regional data, metering and support tiers",
  ],
] as const;
